Repository b1-sycls/sycls, pull requests merged in 2024-08, with the labels that each got.

#158 🐛 bugfix(#157): 카테고리와 콘텐츠 조회부분 수정
  api-test/admin/content-test.http
  api-test/admin/round-test.http
  api-test/user/cast-test.http
  api-test/user/content-test.http
  sycls-admin-api/src/main/java/com/b1/category/CategoryRestController.java
  sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-admin-api/src/main/java/com/b1/content/ContentRestController.java
Labels: 🐛 Bugfix

#162 ♻️ refactor(#152): 공연장 리팩토링
  sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
  sycls-admin-api/src/main/java/com/b1/seat/dto/SeatAddRequestDto.java
  sycls-admin-api/src/main/java/com/b1/seat/dto/SeatUpdateRequestDto.java
  sycls-core/src/main/java/com/b1/seat/SeatRepository.java
  sycls-core/src/main/java/com/b1/seat/entity/Seat.java
Labels: ♻️ Refactor

#164 ♻️ refactor(#163): Admin module SecurityConfig refactoring
  sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
Labels: ♻️ Refactor, 🩹 Fix

#173 ♻️ refactor(#172): @Value 어노테이션 환경변수 명 수정
  sycls-admin-api/src/main/java/com/b1/config/EmailConfig.java
  sycls-admin-api/src/main/java/com/b1/email/EmailService.java
  sycls-admin-api/src/main/java/com/b1/security/JwtProvider.java
  sycls-user-api/src/main/java/com/b1/config/EmailConfig.java
  sycls-user-api/src/main/java/com/b1/email/EmailService.java
  sycls-user-api/src/main/java/com/b1/security/JwtProvider.java
Labels: ♻️ Refactor

#174 ♻️ refactor(#166): 공연장 리팩토링
  sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeRestController.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeService.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeAddRequestDto.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeDeleteRequestDto.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeUpdateRequestDto.java
  sycls-core/src/main/java/com/b1/seat/SeatRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeQueryRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
Labels: ♻️ Refactor

#175 Refactor/172 user
  sycls-admin-api/src/main/java/com/b1/auth/AuthRestController.java
  sycls-admin-api/src/main/java/com/b1/auth/AuthService.java
  sycls-admin-api/src/main/java/com/b1/config/EmailConfig.java
  sycls-admin-api/src/main/java/com/b1/email/EmailService.java
  sycls-admin-api/src/main/resources/application.yml
  sycls-common/src/main/java/com/b1/exception/errorcode/TokenErrorCode.java
  sycls-core/build.gradle
  sycls-user-api/src/main/java/com/b1/auth/AuthRestController.java
  sycls-user-api/src/main/java/com/b1/auth/AuthService.java
  sycls-user-api/src/main/java/com/b1/config/EmailConfig.java
  sycls-user-api/src/main/java/com/b1/email/EmailService.java
  sycls-user-api/src/main/java/com/b1/security/JwtAuthorizationFilter.java
  sycls-user-api/src/main/java/com/b1/security/JwtProvider.java
  sycls-user-api/src/main/resources/application.yml
Labels: ♻️ Refactor

#176 ♻️ refactor(#160): 좌석 예매
  sycls-admin-api/src/main/java/com/b1/security/JwtProvider.java
  sycls-common/src/main/java/com/b1/config/TossConfig.java
  sycls-common/src/main/java/com/b1/constant/ReservationConstant.java
  sycls-common/src/main/java/com/b1/constant/TossConstant.java
  sycls-core/src/main/resources/application-core.yml
  sycls-user-api/src/main/java/com/b1/payment/PaymentController.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentRestController.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentService.java
  sycls-user-api/src/main/java/com/b1/payment/dto/ClientResponseDto.java
  sycls-user-api/src/main/java/com/b1/payment/dto/TossConfirmRequestDto.java
  sycls-user-api/src/main/java/com/b1/payment/dto/TossPaymentRestResponse.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationRestController.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationReserveRequestDto.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeReservationLogHelper.java
Labels: ♻️ Refactor

#179 Refactor/172 user refreshtoken 재발급 api refactoring
  sycls-admin-api/src/main/java/com/b1/auth/AuthRestController.java
  sycls-admin-api/src/main/java/com/b1/auth/AuthService.java
  sycls-admin-api/src/main/java/com/b1/auth/CodeHelper.java
  sycls-admin-api/src/main/java/com/b1/auth/entity/BlacklistToken.java
  sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-admin-api/src/main/java/com/b1/security/JwtAuthorizationFilter.java
  sycls-admin-api/src/main/java/com/b1/security/JwtLogoutHandler.java
  sycls-admin-api/src/main/java/com/b1/security/JwtProvider.java
  sycls-admin-api/src/main/resources/application.yml
  sycls-common/src/main/java/com/b1/constant/TokenConstants.java
  sycls-core/build.gradle
  sycls-core/src/main/java/com/b1/token/entity/BlacklistToken.java
  sycls-core/src/main/java/com/b1/token/entity/Code.java
  sycls-core/src/main/java/com/b1/token/entity/Token.java
  sycls-core/src/main/java/com/b1/token/repository/BlacklistTokenRepository.java
  sycls-core/src/main/java/com/b1/token/repository/CodeRepository.java
  sycls-core/src/main/java/com/b1/token/repository/TokenRepository.java
  sycls-user-api/src/main/java/com/b1/auth/AuthRestController.java
  sycls-user-api/src/main/java/com/b1/auth/AuthService.java
  sycls-user-api/src/main/java/com/b1/auth/CodeHelper.java
  sycls-user-api/src/main/java/com/b1/auth/entity/BlacklistToken.java
  sycls-user-api/src/main/java/com/b1/auth/entity/Code.java
  sycls-user-api/src/main/java/com/b1/auth/repository/BlacklistTokenRepository.java
  sycls-user-api/src/main/java/com/b1/auth/repository/CodeRepository.java
  sycls-user-api/src/main/java/com/b1/auth/repository/TokenRepository.java
  sycls-user-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-user-api/src/main/java/com/b1/security/JwtLogoutHandler.java
  sycls-user-api/src/main/java/com/b1/security/JwtProvider.java
Labels: ♻️ Refactor

#182 ♻️ refactor(#181): 예매 기능 리팩토링
  sycls-core/src/main/java/com/b1/seatgrade/SeatReservationLogRepository.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationRestController.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationService.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationGetOccupiedResponseDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationGetRequestDto.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeReservationLogHelper.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeRestController.java
Labels: ♻️ Refactor

#183 ♻️ refactor(#177): 결제
  sycls-admin-api/src/main/resources/application.yml
  sycls-common/src/main/java/com/b1/exception/customexception/TossPaymentException.java
  sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalPaymentException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/PaymentErrorCode.java
  sycls-common/src/main/java/com/b1/exception/exceptionhandler/ApiExceptionHandler.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatReservationLogRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/entity/SeatGrade.java
  sycls-core/src/main/java/com/b1/ticket/TicketService.java
  sycls-core/src/main/java/com/b1/ticket/entity/Ticket.java
  sycls-user-api/src/main/java/com/b1/payment/PaymentController.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentRestController.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentService.java
  sycls-user-api/src/main/java/com/b1/payment/dto/PaymentSuccessRequestDto.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeReservationLogHelper.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketHelper.java
Labels: ♻️ Refactor

#186 ♻️ refactor: 예매 리팩토링
  sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
  sycls-admin-api/src/main/java/com/b1/review/ReviewHelper.java
  sycls-admin-api/src/main/java/com/b1/review/ReviewService.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeService.java
  sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatReservationLogRepository.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationRestController.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationService.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeReservationLogHelper.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeService.java
Labels: ♻️ Refactor

#187 Refactor/172 user mail yml 수정
  sycls-admin-api/src/main/java/com/b1/config/EmailConfig.java
  sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-admin-api/src/main/java/com/b1/email/EmailService.java
  sycls-admin-api/src/main/resources/application.yml
  sycls-core/src/main/resources/application-core.yml
  sycls-user-api/src/main/java/com/b1/auth/AuthRestController.java
  sycls-user-api/src/main/java/com/b1/config/EmailConfig.java
  sycls-user-api/src/main/java/com/b1/email/EmailService.java
  sycls-user-api/src/main/resources/application.yml
Labels: ♻️ Refactor

#188 ♻️ refactor(#172): /user/me API URI 수정
  sycls-admin-api/src/main/java/com/b1/user/UserRestController.java
  sycls-user-api/src/main/java/com/b1/user/UserRestController.java
Labels: ♻️ Refactor

#191 ♻️ refactor(#189): yml 파일 수정
  sycls-admin-api/src/main/resources/application.yml
  sycls-core/src/main/resources/application-core.yml
  sycls-user-api/src/main/resources/application.yml
Labels: ♻️ Refactor

#194 ♻️ refactor(#193): yml 파일 수정
  sycls-admin-api/src/main/resources/application.yml
  sycls-user-api/src/main/resources/application.yml
Labels: ♻️ Refactor

#201 Refactor/199 전체 리팩터링
  sycls-admin-api/src/main/java/com/b1/config/EmailConfig.java
  sycls-admin-api/src/main/java/com/b1/email/EmailService.java
  sycls-admin-api/src/main/resources/application.yml
  sycls-core/src/main/java/com/b1/config/RedisConfig.java
  sycls-core/src/main/resources/application-core.yml
  sycls-user-api/src/main/java/com/b1/config/EmailConfig.java
  sycls-user-api/src/main/java/com/b1/config/RedisConfig.java
  sycls-user-api/src/main/java/com/b1/email/EmailService.java
  sycls-user-api/src/main/resources/application.yml
Labels: ♻️ Refactor

#204 ♻️ refactor(#202): RedisConfig 업데이트
  sycls-core/src/main/java/com/b1/config/RedisConfig.java
Labels: 🐛 Bugfix, ♻️ Refactor

#209 ♻️ refactor(#206): 리뷰 쿼리 수정 및 리스폰스 값 변경
  api-test/user/review-test.http
  sycls-admin-api/src/main/java/com/b1/review/ReviewHelper.java
  sycls-admin-api/src/main/java/com/b1/review/ReviewRestController.java
  sycls-admin-api/src/main/java/com/b1/review/ReviewService.java
  sycls-admin-api/src/main/java/com/b1/review/dto/ReviewSearchCondRequestDto.java
  sycls-core/src/main/java/com/b1/review/ReviewQueryRepository.java
  sycls-core/src/main/java/com/b1/review/dto/ReviewGetAdminResponseDto.java
  sycls-core/src/main/java/com/b1/review/dto/ReviewGetAllResponseDto.java
  sycls-core/src/main/java/com/b1/review/dto/ReviewGetUserResponseDto.java
  sycls-user-api/src/main/java/com/b1/review/ReviewHelper.java
  sycls-user-api/src/main/java/com/b1/review/ReviewRestController.java
  sycls-user-api/src/main/java/com/b1/review/ReviewService.java
Labels: ♻️ Refactor

#216 🎉 feat(#213): 티켓 조회
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
  sycls-core/src/main/java/com/b1/ticket/TicketQueryRepository.java
  sycls-core/src/main/java/com/b1/ticket/dto/TicketGetAllDto.java
  sycls-core/src/main/java/com/b1/ticket/dto/TicketGetDetailDto.java
  sycls-core/src/main/resources/application-core.yml
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketHelper.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketRestController.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketService.java
  sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetAllUserResponseDto.java
  sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetDetailCastResponseDto.java
  sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetDetailUserResponseDto.java
Labels: 🎉Feature

#219 ♻️ refactor(#217): 공연 조회
  sycls-core/build.gradle
  sycls-core/src/main/java/com/b1/config/RedisConfig.java
  sycls-user-api/build.gradle
  sycls-user-api/src/main/java/com/b1/ticket/TicketService.java
  sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetDetailCastResponseDto.java
  sycls-user-api/src/main/java/com/b1/ticket/dto/TicketGetDetailUserResponseDto.java
Labels: ♻️ Refactor

#227 ♻️ refactor(#226): yml 수정 및 사용하지 않는 의존성 제거
  sycls-core/build.gradle
  sycls-core/src/main/java/com/b1/config/RedisConfig.java
  sycls-core/src/main/resources/application-core.yml
Labels: ♻️ Refactor

#228 🎉 feat(#220): User Social Login with Kakao feature update
  .gitignore
  sycls-admin-api/src/main/java/com/b1/user/UserService.java
  sycls-core/src/main/java/com/b1/user/UserRepository.java
  sycls-core/src/main/java/com/b1/user/entity/User.java
  sycls-user-api/src/main/java/com/b1/config/RestTemplateConfig.java
  sycls-user-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-user-api/src/main/java/com/b1/security/JwtAuthenticationFilter.java
  sycls-user-api/src/main/java/com/b1/user/KakaoRestController.java
  sycls-user-api/src/main/java/com/b1/user/KakaoService.java
  sycls-user-api/src/main/java/com/b1/user/UserHelper.java
  sycls-user-api/src/main/java/com/b1/user/UserService.java
  sycls-user-api/src/main/java/com/b1/user/dto/KakaoUserInfoResponseDto.java
  sycls-user-api/src/main/java/com/b1/user/dto/UserKakaoProfileUpdateRequestDto.java
  sycls-user-api/src/main/resources/application.yml
Labels: 🎉Feature

#229 🎉 feat: 배포 파일 생성
  .github/workflows/cd-admin.yml
  .github/workflows/cd-user.yml
  appspec.yml
  sycls-admin-api/Dockerfile
  sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-core/build.gradle
  sycls-user-api/Dockerfile
  sycls-user-api/src/main/java/com/b1/config/WebSecurityConfig.java
Labels: 🎉Feature

#230 ♻️ refactor(#223): 좌석 예매 동시성 제어
  build.gradle
  sycls-common/src/main/java/com/b1/constant/PaymentConstants.java
  sycls-common/src/main/java/com/b1/constant/ReservationConstants.java
  sycls-core/build.gradle
  sycls-core/src/main/java/com/b1/config/RedisConfig.java
  sycls-core/src/main/java/com/b1/payment/PaymentRepository.java
  sycls-core/src/main/java/com/b1/reservation/ReservationRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatReservationLogRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/entity/SeatGradeReservationLog.java
  sycls-core/src/main/java/com/b1/seatgrade/entity/SeatGradeReservationLogStatus.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentHelper.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentRestController.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentService.java
  sycls-user-api/src/main/java/com/b1/payment/dto/PaymentSuccessRequestDto.java
  sycls-user-api/src/main/java/com/b1/payment/dto/TossConfirmRequestDto.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationHelper.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationRestController.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationService.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationAddRequestDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationAddResponseDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationGetDetailResponseDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationGetOccupiedResponseDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationGetResponseDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationReleaseRequestDto.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeReservationLogHelper.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketHelper.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketService.java
Labels: ♻️ Refactor

#235 🐛 bugfix: user github actions yml파일수정
  .github/workflows/cd-admin.yml
  .github/workflows/cd-user.yml
Labels: 🐛 Bugfix

#236 🎉 MERGE : dev merge
  .github/workflows/cd-admin.yml
  .github/workflows/cd-user.yml
Labels: 🐛 Bugfix

#241 🐛 bugfix(#240): 좌석 등록시 발생하는 에러 해결
  sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java
Labels: 🐛 Bugfix

#242 ♻️ refactor(#226): 사용하지 않는 클래스와 의존성 제거
  sycls-admin-api/src/main/java/com/b1/category/CategoryRestController.java
  sycls-admin-api/src/main/java/com/b1/category/CategoryService.java
  sycls-admin-api/src/main/java/com/b1/content/dto/ContentSearchCondRequest.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceController.java
  sycls-admin-api/src/main/java/com/b1/round/RoundService.java
  sycls-admin-api/src/main/java/com/b1/round/dto/RoundSearchCondRequest.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatController.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeController.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeService.java
  sycls-common/src/main/java/com/b1/constant/AuthConstants.java
  sycls-common/src/main/java/com/b1/constant/EmailConstants.java
  sycls-common/src/main/java/com/b1/constant/PaymentConstants.java
  sycls-common/src/main/java/com/b1/constant/ReservationConstants.java
  sycls-common/src/main/java/com/b1/constant/TokenConstants.java
  sycls-user-api/src/main/java/com/b1/content/dto/ContentSearchCondRequest.java
  sycls-user-api/src/main/java/com/b1/place/PlaceController.java
  sycls-user-api/src/main/java/com/b1/place/PlaceService.java
  sycls-user-api/src/main/java/com/b1/review/ReviewController.java
  sycls-user-api/src/main/java/com/b1/round/dto/RoundSearchCondRequest.java
  sycls-user-api/src/main/java/com/b1/seat/SeatController.java
  sycls-user-api/src/main/java/com/b1/seat/SeatService.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeController.java
Labels: ♻️ Refactor

#244 🎉 MERGE : dev merge
  sycls-admin-api/src/main/java/com/b1/category/CategoryRestController.java
  sycls-admin-api/src/main/java/com/b1/category/CategoryService.java
  sycls-admin-api/src/main/java/com/b1/content/dto/ContentSearchCondRequest.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceController.java
  sycls-admin-api/src/main/java/com/b1/round/RoundService.java
  sycls-admin-api/src/main/java/com/b1/round/dto/RoundSearchCondRequest.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeController.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeService.java
  sycls-common/src/main/java/com/b1/constant/AuthConstants.java
  sycls-common/src/main/java/com/b1/constant/EmailConstants.java
  sycls-common/src/main/java/com/b1/constant/PaymentConstants.java
  sycls-common/src/main/java/com/b1/constant/ReservationConstants.java
  sycls-common/src/main/java/com/b1/constant/TokenConstants.java
  sycls-user-api/src/main/java/com/b1/content/dto/ContentSearchCondRequest.java
  sycls-user-api/src/main/java/com/b1/place/PlaceController.java
  sycls-user-api/src/main/java/com/b1/place/PlaceService.java
  sycls-user-api/src/main/java/com/b1/review/ReviewController.java
  sycls-user-api/src/main/java/com/b1/round/dto/RoundSearchCondRequest.java
  sycls-user-api/src/main/java/com/b1/seat/SeatController.java
  sycls-user-api/src/main/java/com/b1/seat/SeatService.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeController.java
Labels: ♻️ Refactor

#247 ♻️ refactor(246): docker 실행 명령어 name 수정
  .github/workflows/cd-user.yml
Labels: ♻️ Refactor

#248 🎉 MERGE : dev merge
  .github/workflows/cd-user.yml
Labels: ♻️ Refactor

#251 🐛 bugfix(#250): 회차의 공연장 변경시 좌석등급 비활성화
  sycls-admin-api/src/main/java/com/b1/round/RoundService.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
Labels: 🐛 Bugfix

#252 🎉 MERGE : dev merge
  sycls-admin-api/src/main/java/com/b1/round/RoundService.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
Labels: 🐛 Bugfix

#257 🐛 bugfix(#253): 결제 만료 후 결제 시도 추가 검증
  sycls-common/src/main/java/com/b1/constant/ReservationConstant.java
  sycls-common/src/main/java/com/b1/constant/ReservationConstants.java
  sycls-common/src/main/java/com/b1/exception/customexception/ReservationNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatReservationAlreadyDisableException.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatReservationLogNotAvailableException.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatReservationLogNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/ReservationErrorCode.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentService.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationAddRequestDto.java
Labels: 🐛 Bugfix

#258 🎉 MERGE : dev merge
  sycls-common/src/main/java/com/b1/constant/ReservationConstant.java
  sycls-common/src/main/java/com/b1/constant/ReservationConstants.java
  sycls-common/src/main/java/com/b1/exception/customexception/ReservationNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatReservationAlreadyDisableException.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatReservationLogNotAvailableException.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatReservationLogNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/ReservationErrorCode.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentService.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationAddRequestDto.java
Labels: 🐛 Bugfix

#261 ♻️ refactor(220): 예외 반환에 "valid" message 추가
  sycls-common/src/main/java/com/b1/exception/exceptionhandler/ValidExceptionHandler.java
  sycls-common/src/main/java/com/b1/globalresponse/ErrorResponseDto.java
Labels: ♻️ Refactor

#263 Refactor/259 공연 상태변경 기능 리펙터링
  sycls-core/src/main/java/com/b1/content/ContentQueryRepository.java
Labels: ♻️ Refactor

#269 ♻️ refactor(265): place전체조회(Enable)
  api-test/admin/place-test.http
  sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
  sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
  sycls-core/src/main/java/com/b1/place/dto/PlaceGetEnableResponseDto.java
Labels: 🎉Feature

#270 ♻️ refactor(265): 카테고리전체조회(Enable)
  sycls-admin-api/src/main/java/com/b1/category/CategoryHelper.java
  sycls-admin-api/src/main/java/com/b1/category/CategoryRestController.java
  sycls-admin-api/src/main/java/com/b1/category/CategoryService.java
  sycls-core/src/main/java/com/b1/category/CategoryQueryRepository.java
  sycls-core/src/main/java/com/b1/category/CategoryRepository.java
  sycls-core/src/main/java/com/b1/category/dto/CategoryGetEnableResponseDto.java
Labels: 🎉Feature

#271 🎉 MERGE : dev merge
  api-test/admin/place-test.http
  sycls-admin-api/src/main/java/com/b1/category/CategoryHelper.java
  sycls-admin-api/src/main/java/com/b1/category/CategoryRestController.java
  sycls-admin-api/src/main/java/com/b1/category/CategoryService.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
  sycls-core/src/main/java/com/b1/category/CategoryQueryRepository.java
  sycls-core/src/main/java/com/b1/category/CategoryRepository.java
  sycls-core/src/main/java/com/b1/category/dto/CategoryGetEnableResponseDto.java
  sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
  sycls-core/src/main/java/com/b1/place/dto/PlaceGetEnableResponseDto.java
Labels: ♻️ Refactor

#279 ♻️ refactor(276) : 회차기능 리펙토링
  sycls-admin-api/src/main/java/com/b1/round/RoundService.java
  sycls-admin-api/src/main/java/com/b1/round/dto/RoundAddRequestDto.java
  sycls-common/src/main/java/com/b1/exception/customexception/InvalidDateTimeException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/RoundErrorCode.java
Labels: ♻️ Refactor

#282 🎉 feat(#281): 더미데이터 생성 로직 작성
  sycls-admin-api/build.gradle
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerRestController.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerService.java
Labels: 🎉Feature

#283 🎉 MERGE : dev merge
  sycls-admin-api/build.gradle
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerRestController.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerService.java
Labels: 🎉Feature

#292 🎉 MERGE : dev merge
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerRestController.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerService.java
Labels: 🎉Feature

#295 ♻️ refactomr(#294): 더미 데이터 추가 업데이트
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerRestController.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerService.java
  sycls-core/src/main/java/com/b1/round/RoundRepository.java
  sycls-core/src/main/java/com/b1/seat/SeatRepository.java
Labels: ♻️ Refactor

#296 🎉 MERGE : dev merge
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerRestController.java
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerService.java
  sycls-core/src/main/java/com/b1/round/RoundRepository.java
  sycls-core/src/main/java/com/b1/seat/SeatRepository.java
Labels: 🎉Feature

#299 ♻️ refactor(#298): 좌석등급 더미데이터 등록 로직 수정
  api-test/admin/datafaker-test.http
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
  sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
Labels: ♻️ Refactor

#300 🎉 MERGE : dev merge
  api-test/admin/datafaker-test.http
  sycls-admin-api/src/main/java/com/b1/datafaker/DatafakerHelper.java
  sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
Labels: ♻️ Refactor

#303 🐛 bugfix(#302): request dto valid 수정
  sycls-admin-api/src/main/java/com/b1/round/dto/RoundAddRequestDto.java
Labels: 🐛 Bugfix

#304 🎉 MERGE : dev merge
  sycls-admin-api/src/main/java/com/b1/round/dto/RoundAddRequestDto.java
Labels: 🐛 Bugfix

#307 Bugfix/305 rounds
  sycls-admin-api/src/main/java/com/b1/round/dto/RoundAddRequestDto.java
  sycls-admin-api/src/main/resources/application.yml
  sycls-common/src/main/java/com/b1/exception/errorcode/S3ErrorCode.java
  sycls-common/src/main/java/com/b1/exception/exceptionhandler/ValidExceptionHandler.java
Labels: 🐛 Bugfix, ♻️ Refactor

#308 🎉 MERGE : dev merge
  sycls-admin-api/src/main/java/com/b1/round/dto/RoundAddRequestDto.java
  sycls-admin-api/src/main/resources/application.yml
  sycls-common/src/main/java/com/b1/exception/errorcode/S3ErrorCode.java
  sycls-common/src/main/java/com/b1/exception/exceptionhandler/ValidExceptionHandler.java
Labels: 🐛 Bugfix, ♻️ Refactor

#314 🎉 feat(#313): 등록 요청 동시성 제어
  sycls-admin-api/src/main/java/com/b1/content/ContentRestController.java
  sycls-admin-api/src/main/java/com/b1/content/ContentService.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatRestController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
  sycls-common/build.gradle
  sycls-common/src/main/java/com/b1/exception/customexception/AddLockException.java
  sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalInterruptedException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/CommonErrorCode.java
  sycls-common/src/main/java/com/b1/exception/exceptionhandler/ApiExceptionHandler.java
  sycls-core/build.gradle
  sycls-core/src/main/java/com/b1/aop/AopForTransaction.java
  sycls-core/src/main/java/com/b1/aop/CustomSpringELParser.java
  sycls-core/src/main/java/com/b1/aop/DistributedLock.java
  sycls-core/src/main/java/com/b1/aop/DistributedLockAop.java
  sycls-user-api/build.gradle
Labels: 🎉Feature

#315 🎉 MERGE : dev merge
  sycls-admin-api/src/main/java/com/b1/content/ContentRestController.java
  sycls-admin-api/src/main/java/com/b1/content/ContentService.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatRestController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
  sycls-common/build.gradle
  sycls-common/src/main/java/com/b1/exception/customexception/AddLockException.java
  sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalInterruptedException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/CommonErrorCode.java
  sycls-common/src/main/java/com/b1/exception/exceptionhandler/ApiExceptionHandler.java
  sycls-core/build.gradle
  sycls-core/src/main/java/com/b1/aop/AopForTransaction.java
  sycls-core/src/main/java/com/b1/aop/CustomSpringELParser.java
  sycls-core/src/main/java/com/b1/aop/DistributedLock.java
  sycls-core/src/main/java/com/b1/aop/DistributedLockAop.java
  sycls-user-api/build.gradle
Labels: 🎉Feature

#318 Docs/316 read me
  README.md
Labels: 📄 Docs

#319 Refactor/309 redis
  sycls-common/src/main/java/com/b1/constant/PaymentConstants.java
  sycls-common/src/main/java/com/b1/constant/RedissonConstants.java
  sycls-common/src/main/java/com/b1/constant/ReservationConstants.java
  sycls-core/src/main/java/com/b1/payment/PaymentRepository.java
  sycls-core/src/main/java/com/b1/redis/RedissonRepository.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentHelper.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationHelper.java
Labels: ♻️ Refactor

#320 🎉 MERGE : dev merge
  sycls-common/src/main/java/com/b1/constant/PaymentConstants.java
  sycls-common/src/main/java/com/b1/constant/RedissonConstants.java
  sycls-common/src/main/java/com/b1/constant/ReservationConstants.java
  sycls-core/src/main/java/com/b1/payment/PaymentRepository.java
  sycls-core/src/main/java/com/b1/redis/RedissonRepository.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentHelper.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationHelper.java
Labels: ♻️ Refactor

#323 Bugfix/321 seatgrade
  sycls-admin-api/src/main/java/com/b1/place/dto/PlaceAddRequestDto.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeAddRequestDto.java
Labels: 🐛 Bugfix

#324 main에서 dev로 merge
  README.md
  sycls-admin-api/src/main/java/com/b1/place/dto/PlaceAddRequestDto.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeAddRequestDto.java
Labels: 🐛 Bugfix
