Repository b1-sycls/sycls, pull requests merged in 2024-07, with the labels that each got.

#6 ♻️ refactor(환경): yml 파일 설정
  sycls-admin-api/src/main/resources/application.yml
  sycls-core/src/main/resources/application-core.yml
  sycls-user-api/src/main/resources/application.yml
Labels: ♻️ Refactor

#25 ♻️ refactor(공통): Entity 재설계
  sycls-admin-api/build.gradle
  sycls-common/src/main/java/com/b1/globalresponse/ErrorResponseDto.java
  sycls-common/src/main/java/com/b1/globalresponse/RestApiResponseDto.java
  sycls-core/src/main/java/com/b1/common/PageResponseDto.java
  sycls-core/src/main/java/com/b1/config/JpaAuditingConfig.java
  sycls-core/src/main/java/com/b1/config/QueryDslConfig.java
  sycls-core/src/main/java/com/b1/content/entity/Content.java
  sycls-core/src/main/java/com/b1/content/entity/ContentDetailImage.java
  sycls-core/src/main/java/com/b1/content/entity/Round.java
  sycls-core/src/main/java/com/b1/place/ContentRepository.java
  sycls-core/src/main/java/com/b1/place/entity/Place.java
  sycls-core/src/main/java/com/b1/review/entity/Review.java
  sycls-core/src/main/java/com/b1/seat/entity/SeatGrade.java
  sycls-user-api/build.gradle
Labels: ♻️ Refactor

#27 🎉feature: 공연장 CRUD
  api-test/admin/place-test.http
  sycls-admin-api/src/main/java/com/b1/place/PlaceAdapter.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceController.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
  sycls-admin-api/src/main/java/com/b1/place/dto/PlaceAddRequestDto.java
  sycls-admin-api/src/main/java/com/b1/place/dto/PlaceSearchCondRequestDto.java
  sycls-admin-api/src/main/java/com/b1/place/dto/PlaceUpdateRequestDto.java
  sycls-admin-api/src/main/java/com/b1/ticket/TicketService.java
  sycls-common/src/main/java/com/b1/exception/customexception/PlaceAlreadyDeletedException.java
  sycls-common/src/main/java/com/b1/exception/customexception/PlaceNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalAlreadyDeletedException.java
  sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/PlaceErrorCode.java
  sycls-common/src/main/java/com/b1/globalresponse/ErrorResponseDto.java
  sycls-common/src/main/java/com/b1/globalresponse/RestApiResponseDto.java
  sycls-core/src/main/java/com/b1/category/CategoryAdapter.java
  sycls-core/src/main/java/com/b1/config/JpaConfig.java
  sycls-core/src/main/java/com/b1/content/entity/Content.java
  sycls-core/src/main/java/com/b1/place/ContentAdapter.java
  sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
  sycls-core/src/main/java/com/b1/place/PlaceRepository.java
  sycls-core/src/main/java/com/b1/place/dto/PlaceGetResponseDto.java
  sycls-core/src/main/java/com/b1/place/entity/Place.java
  sycls-core/src/main/java/com/b1/place/entity/PlaceStatus.java
  sycls-core/src/main/java/com/b1/review/ReviewAdapter.java
  sycls-core/src/main/java/com/b1/review/entity/Review.java
  sycls-core/src/main/java/com/b1/seat/SeatAdapter.java
  sycls-core/src/main/java/com/b1/ticket/TicketAdapter.java
  sycls-core/src/main/java/com/b1/ticket/TicketService.java
  sycls-core/src/main/java/com/b1/user/UserAdapter.java
  sycls-core/src/main/java/com/b1/user/UserService.java
  sycls-core/src/main/java/com/b1/user/entity/User.java
Labels: 🎉Feature

#40 🎉feature: 좌석 CRUD
  api-test/admin/seat-test.http
  sycls-admin-api/src/main/java/com/b1/place/PlaceAdapter.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
  sycls-admin-api/src/main/java/com/b1/place/dto/SeatUpdateRequestDto.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatAdapter.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatRestController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
  sycls-admin-api/src/main/java/com/b1/seat/dto/SeatAddRequestDto.java
  sycls-admin-api/src/main/java/com/b1/seat/dto/SeatGetAllResponseDto.java
  sycls-admin-api/src/main/java/com/b1/seat/dto/SeatGetResponseDto.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatAlreadyDeletedException.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/SeatErrorCode.java
  sycls-core/src/main/java/com/b1/seat/SeatRepository.java
  sycls-core/src/main/java/com/b1/seat/entity/Seat.java
  sycls-core/src/main/java/com/b1/seat/entity/SeatStatus.java
Labels: 🎉Feature

#54 🎉feature: 사용자 리뷰 CRUD
  sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
  sycls-common/src/main/java/com/b1/exception/customexception/ReviewAlreadyDeletedException.java
  sycls-common/src/main/java/com/b1/exception/customexception/ReviewNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/ReviewErrorCode.java
  sycls-core/src/main/java/com/b1/review/ReviewQueryRepository.java
  sycls-core/src/main/java/com/b1/review/dto/ReviewGetAllResponseDto.java
  sycls-core/src/main/java/com/b1/review/entity/Review.java
  sycls-core/src/main/java/com/b1/review/entity/ReviewStatus.java
  sycls-user-api/src/main/java/com/b1/review/ReviewController.java
  sycls-user-api/src/main/java/com/b1/review/ReviewHelper.java
  sycls-user-api/src/main/java/com/b1/review/ReviewRestController.java
  sycls-user-api/src/main/java/com/b1/review/ReviewService.java
  sycls-user-api/src/main/java/com/b1/review/dto/ReviewAddRequestDto.java
  sycls-user-api/src/main/java/com/b1/review/dto/ReviewUpdateRequestDto.java
Labels: 🎉Feature

#80 refactor/78-entity-add-final
  sycls-core/src/main/java/com/b1/category/entity/Category.java
  sycls-core/src/main/java/com/b1/content/entity/Content.java
  sycls-core/src/main/java/com/b1/round/entity/Round.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
  sycls-user-api/src/main/resources/application.yml
Labels: ♻️ Refactor, 🩹 Fix

#85 🎉feature: 유저 이메일 찾기, 프로필 조회 기능 구현
  sycls-common/src/main/java/com/b1/exception/customexception/EmailCodeException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/EmailAuthErrorCode.java
  sycls-core/src/main/java/com/b1/user/UserRepository.java
  sycls-core/src/main/java/com/b1/user/entity/UserStatus.java
  sycls-core/src/main/resources/application-core.yml
  sycls-user-api/src/main/java/com/b1/auth/AuthRestController.java
  sycls-user-api/src/main/java/com/b1/auth/AuthService.java
  sycls-user-api/src/main/java/com/b1/auth/CodeHelper.java
  sycls-user-api/src/main/java/com/b1/auth/dto/FindEmailRequestDto.java
  sycls-user-api/src/main/java/com/b1/auth/repository/CodeRepository.java
  sycls-user-api/src/main/java/com/b1/user/UserHelper.java
  sycls-user-api/src/main/java/com/b1/user/UserRestController.java
  sycls-user-api/src/main/java/com/b1/user/UserService.java
  sycls-user-api/src/main/java/com/b1/user/dto/UserProfileResponseDto.java
Labels: 🎉Feature

#88 🎉feature: 좌석-등급CRUD
  api-test/admin/seatGrade-test.http
  api-test/user/seatGrade-test.http
  sycls-admin-api/src/main/java/com/b1/place/PlaceController.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
  sycls-admin-api/src/main/java/com/b1/review/ReviewRestController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatRestController.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeRestController.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeService.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeAddRequestDto.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeDeleteRequestDto.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeGetAllResponseDto.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/dto/SeatGradeUpdateRequestDto.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatGradeAlreadyDeletedException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/SeatGradeErrorCode.java
  sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
  sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
  sycls-core/src/main/java/com/b1/round/dto/RoundCheckPlaceResponseDto.java
  sycls-core/src/main/java/com/b1/seat/SeatRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeQueryRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/dto/SeatGradeAdminGetResponseDto.java
  sycls-core/src/main/java/com/b1/seatgrade/dto/SeatGradeUserGetDto.java
  sycls-core/src/main/java/com/b1/seatgrade/entity/SeatGrade.java
  sycls-core/src/main/java/com/b1/seatgrade/entity/SeatGradeStatus.java
  sycls-core/src/main/java/com/b1/seatgrade/entity/SeatGradeType.java
  sycls-core/src/main/resources/application-core.yml
  sycls-user-api/src/main/java/com/b1/review/ReviewController.java
  sycls-user-api/src/main/java/com/b1/review/ReviewRestController.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeRestController.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeService.java
  sycls-user-api/src/main/java/com/b1/seatgrade/dto/SeatGradeGetAllResponseDto.java
  sycls-user-api/src/main/java/com/b1/seatgrade/dto/SeatGradeGetResponseDto.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketService.java
Labels: 🎉Feature

#96 🎉feature: 출연진 CRUD
  api-test/admin/cast-test.http
  api-test/user/cast-test.http
  sycls-admin-api/src/main/java/com/b1/cast/CastHelper.java
  sycls-admin-api/src/main/java/com/b1/cast/CastRestController.java
  sycls-admin-api/src/main/java/com/b1/cast/CastService.java
  sycls-admin-api/src/main/java/com/b1/cast/dto/CastAddRequestDto.java
  sycls-admin-api/src/main/java/com/b1/cast/dto/CastUpdateRequestDto.java
  sycls-admin-api/src/main/java/com/b1/content/ContentService.java
  sycls-common/src/main/java/com/b1/constant/S3Constant.java
  sycls-common/src/main/java/com/b1/exception/customexception/CastAlreadyCanceledException.java
  sycls-common/src/main/java/com/b1/exception/customexception/CastNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/CastErrorCode.java
  sycls-common/src/main/java/com/b1/s3/S3Type.java
  sycls-common/src/main/java/com/b1/s3/S3Uploader.java
  sycls-common/src/main/java/com/b1/s3/S3UrlPathType.java
  sycls-common/src/main/java/com/b1/s3/S3Util.java
  sycls-core/src/main/java/com/b1/cast/CastRepository.java
  sycls-core/src/main/java/com/b1/cast/entity/Cast.java
  sycls-core/src/main/java/com/b1/cast/entity/CastQueryRepository.java
  sycls-core/src/main/java/com/b1/cast/entity/CastStatus.java
  sycls-core/src/main/java/com/b1/cast/entity/dto/CastGetAdminResponseDto.java
  sycls-core/src/main/java/com/b1/cast/entity/dto/CastGetUserResponseDto.java
  sycls-core/src/main/java/com/b1/category/CategoryQueryRepository.java
  sycls-core/src/main/java/com/b1/content/ContentQueryRepository.java
  sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
  sycls-user-api/src/main/java/com/b1/cast/CastHelper.java
  sycls-user-api/src/main/java/com/b1/cast/CastRestController.java
  sycls-user-api/src/main/java/com/b1/cast/CastService.java
Labels: 🎉Feature

#97 🎉feature: 예매 CRD
  sycls-common/src/main/java/com/b1/exception/customexception/SeatReservationAlreadyDisableException.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatReservationLogNotFoundException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/SeatReservationLogErrorCode.java
  sycls-core/src/main/java/com/b1/round/entity/RoundStatus.java
  sycls-core/src/main/java/com/b1/seat/SeatReservationLogRepository.java
  sycls-core/src/main/java/com/b1/seat/entity/SeatReservationLog.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatReservationLogRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/entity/SeatGradeReservationLog.java
  sycls-core/src/main/java/com/b1/seatgrade/entity/SeatGradeReservationLogStatus.java
  sycls-core/src/main/java/com/b1/ticket/entity/Ticket.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationRestController.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationService.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationGetRequestDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationGetResponseDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationReleaseRequestDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationReserveRequestDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationReserveResponseDto.java
  sycls-user-api/src/main/java/com/b1/round/RoundHelper.java
  sycls-user-api/src/main/java/com/b1/seat/SeatReservationLogHelper.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeReservationLogHelper.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketHelper.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketRestController.java
  sycls-user-api/src/main/java/com/b1/ticket/TicketService.java
Labels: 🎉Feature

#105 ♻️ refactor: 회차 상태수정 로직 리펙토링
  api-test/admin/content-test.http
  api-test/admin/round-test.http
  sycls-admin-api/src/main/java/com/b1/round/RoundService.java
  sycls-admin-api/src/main/java/com/b1/seatgrade/SeatGradeHelper.java
  sycls-common/src/main/java/com/b1/exception/customexception/RoundNotFullSeatGradeException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/RoundErrorCode.java
  sycls-core/src/main/java/com/b1/content/ContentQueryRepository.java
  sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
  sycls-core/src/main/java/com/b1/round/dto/RoundSeatGradeStatusDto.java
  sycls-core/src/main/java/com/b1/round/entity/RoundStatus.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeQueryRepository.java
Labels: ♻️ Refactor

#106 ♻️ refactor: 공연장 리팩토링
  sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
  sycls-admin-api/src/main/java/com/b1/round/RoundHelper.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatRestController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
  sycls-admin-api/src/main/java/com/b1/seat/dto/SeatUpdateRequestDto.java
  sycls-common/src/main/java/com/b1/exception/customexception/PlaceCannotUpdateException.java
  sycls-common/src/main/java/com/b1/exception/errorcode/PlaceErrorCode.java
  sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
  sycls-core/src/main/java/com/b1/place/dto/PlaceCheckSeatDto.java
  sycls-core/src/main/java/com/b1/place/entity/Place.java
  sycls-core/src/main/java/com/b1/place/entity/PlaceStatus.java
  sycls-core/src/main/java/com/b1/round/RoundRepository.java
Labels: ♻️ Refactor

#115 ♻️ refactor: 회차 리펙토링
  sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
  sycls-admin-api/src/main/java/com/b1/round/RoundService.java
  sycls-core/src/main/java/com/b1/place/PlaceRepository.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeQueryRepository.java
Labels: ♻️ Refactor

#121 🎉 feat(#120): 회차 단일 간단 조회 기능 구현
  api-test/user/round-test.http
  sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
  sycls-core/src/main/java/com/b1/round/dto/ContentAndRoundGetResponseDto.java
  sycls-user-api/src/main/java/com/b1/round/RoundHelper.java
  sycls-user-api/src/main/java/com/b1/round/RoundRestController.java
  sycls-user-api/src/main/java/com/b1/round/RoundService.java
Labels: 🎉Feature

#123 풀리퀘 충돌 해결
  api-test/user/round-test.http
  sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
  sycls-core/src/main/java/com/b1/round/dto/ContentAndRoundGetResponseDto.java
  sycls-user-api/src/main/java/com/b1/round/RoundHelper.java
  sycls-user-api/src/main/java/com/b1/round/RoundRestController.java
  sycls-user-api/src/main/java/com/b1/round/RoundService.java
Labels: 🐛 Bugfix

#122 ♻️ refactor: 좌석 리펙토링
  sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceRestController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatHelper.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatRestController.java
  sycls-admin-api/src/main/java/com/b1/seat/SeatService.java
  sycls-admin-api/src/main/java/com/b1/seat/dto/SeatUpdateRequestDto.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatCannotAddException.java
  sycls-common/src/main/java/com/b1/exception/customexception/SeatCodeDuplicatedException.java
  sycls-common/src/main/java/com/b1/exception/customexception/global/GlobalCannotAddExcpetion.java
  sycls-common/src/main/java/com/b1/exception/errorcode/SeatErrorCode.java
  sycls-common/src/main/java/com/b1/exception/exceptionhandler/ApiExceptionHandler.java
  sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
  sycls-core/src/main/java/com/b1/seat/SeatRepository.java
Labels: ♻️ Refactor

#141 ♻️ refactor(#140): 매개변수 final 추가 및 리스폰스 반환값 추가
  api-test/user/round-test.http
  sycls-core/src/main/java/com/b1/cast/entity/CastStatus.java
  sycls-core/src/main/java/com/b1/common/PageResponseDto.java
  sycls-core/src/main/java/com/b1/content/entity/ContentDetailImage.java
  sycls-core/src/main/java/com/b1/place/dto/PlaceGetResponseDto.java
  sycls-core/src/main/java/com/b1/place/entity/Place.java
  sycls-core/src/main/java/com/b1/place/entity/PlaceStatus.java
  sycls-core/src/main/java/com/b1/review/dto/ReviewGetAllResponseDto.java
  sycls-core/src/main/java/com/b1/review/entity/ReviewStatus.java
  sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
  sycls-core/src/main/java/com/b1/round/dto/ContentAndRoundGetResponseDto.java
  sycls-core/src/main/java/com/b1/round/dto/RoundDetailInfoAdminResponseDto.java
  sycls-core/src/main/java/com/b1/round/dto/RoundDetailInfoUserResponseDto.java
  sycls-core/src/main/java/com/b1/seat/entity/Seat.java
  sycls-core/src/main/resources/data.sql
  sycls-user-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-user-api/src/main/resources/data.sql
Labels: ♻️ Refactor

#144 ♻️ refactor(#143): 안쓰는 메서드 정리
  sycls-admin-api/src/main/java/com/b1/user/AdminController.java
  sycls-core/src/main/java/com/b1/seatgrade/SeatGradeRepository.java
Labels: ♻️ Refactor

#147 🐛 bugfix(#146): 동적쿼리시 파람으로 보낸 매개변수가 적용이안되는 버그 수정
  api-test/user/content-test.http
  api-test/user/round-test.http
  sycls-admin-api/src/main/java/com/b1/category/CategoryController.java
  sycls-admin-api/src/main/java/com/b1/content/ContentController.java
  sycls-admin-api/src/main/java/com/b1/content/ContentHelper.java
  sycls-admin-api/src/main/java/com/b1/content/ContentRestController.java
  sycls-admin-api/src/main/java/com/b1/content/ContentService.java
  sycls-admin-api/src/main/java/com/b1/content/dto/ContentSearchCondRequest.java
  sycls-admin-api/src/main/java/com/b1/round/RoundHelper.java
  sycls-admin-api/src/main/java/com/b1/round/RoundRestController.java
  sycls-admin-api/src/main/java/com/b1/round/RoundService.java
  sycls-admin-api/src/main/java/com/b1/round/dto/RoundSearchCondRequest.java
  sycls-core/src/main/java/com/b1/round/RoundQueryRepository.java
  sycls-user-api/src/main/java/com/b1/auth/CodeHelper.java
  sycls-user-api/src/main/java/com/b1/category/CategoryController.java
  sycls-user-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-user-api/src/main/java/com/b1/content/ContentController.java
  sycls-user-api/src/main/java/com/b1/content/ContentHelper.java
  sycls-user-api/src/main/java/com/b1/content/ContentRestController.java
  sycls-user-api/src/main/java/com/b1/content/ContentService.java
  sycls-user-api/src/main/java/com/b1/content/dto/ContentSearchCondRequest.java
  sycls-user-api/src/main/java/com/b1/round/RoundController.java
  sycls-user-api/src/main/java/com/b1/round/RoundHelper.java
  sycls-user-api/src/main/java/com/b1/round/RoundRestController.java
  sycls-user-api/src/main/java/com/b1/round/RoundService.java
  sycls-user-api/src/main/java/com/b1/round/dto/RoundSearchCondRequest.java
Labels: 🐛 Bugfix

#150 Feat/100 payment
  sycls-common/src/main/java/com/b1/constant/DomainConstant.java
  sycls-user-api/build.gradle
  sycls-user-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-user-api/src/main/java/com/b1/payment/PaymentController.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentRestController.java
  sycls-user-api/src/main/java/com/b1/payment/TossPaymentService.java
  sycls-user-api/src/main/java/com/b1/payment/dto/ClientResponseDto.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationRestController.java
  sycls-user-api/src/main/java/com/b1/reservation/ReservationService.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/ReservationGetDetailResponseDto.java
  sycls-user-api/src/main/java/com/b1/reservation/dto/SeatGradeReservationDto.java
  sycls-user-api/src/main/java/com/b1/seatgrade/SeatGradeReservationLogHelper.java
  sycls-user-api/src/main/resources/application.yml
Labels: 🎉Feature

#153 ♻️ refactor(#152): 공연장 리팩토링
  sycls-admin-api/src/main/java/com/b1/config/WebSecurityConfig.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceHelper.java
  sycls-admin-api/src/main/java/com/b1/place/PlaceService.java
  sycls-admin-api/src/main/java/com/b1/place/dto/PlaceSearchCondRequestDto.java
  sycls-core/src/main/java/com/b1/common/PageResponseDto.java
  sycls-core/src/main/java/com/b1/place/PlaceQueryRepository.java
  sycls-core/src/main/java/com/b1/place/entity/Place.java
Labels: ♻️ Refactor
